name: "context-update"
on:
  # TODO: remove this
  push:
    branches:
      - master

  schedule:
    # Update context.tf and README.md nightly
    - cron:  '0 0 * * *'

jobs:
  update:
#    TODO: uncomment
#    if: github.event_name == 'schedule'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Update context.tf
        shell: bash
        id: update
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        run: |
          if [[ -f context.tf ]]; then
            echo "Discovered existing context.tf! Fetching most recent version to see if there is an update."
            curl -o context.tf -fsSL https://raw.githubusercontent.com/cloudposse/terraform-null-label/master/exports/context.tf
            if git diff --no-patch --exit-code context.tf; then
              echo "No changes detected! Exiting the job..."
            else
              echo "context.tf file was updated. Need to rebuild README.md."
              make init
              make readme/build
            fi
          else
            echo "This module has not yet been updated to support the context.tf pattern! Please update in order to support automatic updates."
          fi

      - name: Create Pull Request
        uses: cloudposse/actions/github/create-pull-request@0.20.0
        with:
          token: ${{ secrets.PUBLIC_REPO_ACCESS_TOKEN }}
          commit-message: Update context.tf from origin source
          title: Update context.tf
          body: |-
            ## what
            This is an auto-generated PR that updates the context.tf file

            ## why
            To have most recent changes of `context`

          branch: auto-update/context.tf
          base: master
          delete-branch: true
          labels: |
            auto-update
            context
